-- VHDL module instantiation generated by SCUBA Diamond_2.0_Production (151)
-- Module  Version: 4.8
-- Tue Jun 16 16:05:51 2015

-- parameterized module component declaration
component ps2_fifo
    port (Data: in  std_logic_vector(7 downto 0); Clock: in  std_logic; 
        WrEn: in  std_logic; RdEn: in  std_logic; Reset: in  std_logic; 
        Q: out  std_logic_vector(7 downto 0); Empty: out  std_logic; 
        Full: out  std_logic);
end component;

-- parameterized module component instance
__ : ps2_fifo
    port map (Data(7 downto 0)=>__, Clock=>__, WrEn=>__, RdEn=>__, Reset=>__, 
        Q(7 downto 0)=>__, Empty=>__, Full=>__);
